# Generated by Django 5.2.7 on 2025-10-18 21:42

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorySegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        help_text="Позиция части в истории (0..N)"
                    ),
                ),
                (
                    "previous_video_url",
                    models.URLField(
                        help_text="Видео, на основе которого сгенерировано",
                        max_length=1024,
                    ),
                ),
                (
                    "previous_prompt",
                    models.TextField(help_text="Промпт до добавления этой части"),
                ),
                (
                    "used_prompt",
                    models.TextField(help_text="Промпт, добавленный в этой части"),
                ),
                (
                    "new_video_url",
                    models.URLField(
                        help_text="Результирующее видео этой части", max_length=1024
                    ),
                ),
                (
                    "cumulative_prompt",
                    models.TextField(help_text="Полный промпт на данном шаге"),
                ),
                ("job_set_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "frame_image_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_segments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "position"],
                "indexes": [
                    models.Index(
                        fields=["project", "position"],
                        name="generator_s_project_30bd96_idx",
                    )
                ],
                "unique_together": {("project", "position")},
            },
        ),
    ]
