services:
  server:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    container_name: initial_hf_server
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
